# Generated by Django 3.2.4 on 2021-06-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desrciption',
            new_name='description',
        ),
    ]
